-   id: check-robotframework-files
    name: Check for robotframework files
    description: Checking Coding Sytle for robot files
    entry: check-robotframework-files
    language: python
    types: [file]
