repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/msc0953/pre-commit-code-review-hooks
    rev: v1.0.0
    hooks:
    -   id: check-robotframework